# https://docs.codecov.io/docs/codecovyml-reference
codecov:
  notify:
    require_ci_to_pass: no
    wait_for_ci: no

comment: false

coverage:
  precision: 2
  range: "75..95"
  round: nearest

ignore:
  - "Carthage/**"
  - "Datadog/**"
  - "Tests/**"
