# https://docs.codecov.io/docs/codecovyml-reference
codecov:
  notify:
    require_ci_to_pass: yes # do not bother with coverage on CI failures
    wait_for_ci: no # send coverage without waiting for entire CI run

comment: false

coverage:
  precision: 2
  range: "75..95"
  round: nearest

ignore:
  - "Carthage/**"
  - "Datadog/**"
  - "Tests/**"
  - "**/RUMDataModels*.swift"
